### ISSUE TITLE
Linker.LD files current with TD 1.54

### ISSUE THREAD

**Issue by Defragster** [FrankBoesing/snippets#1]
Are these LD files drop in replacements with now current TD 1.54?

These push keep ALL code in FLASH right for empty ITCM with "NOLOAD" ?

**Comment by FrankBoesing** [comment]
Hi Tim, 

no, they are for a old version. It has no chance to get supported by pjrc, and I didn't feel like updating it.

**Comment by Defragster** [comment]
Hi Frank,
I was thinking I might have reason to try it for a test in the next week.

**Comment by FrankBoesing** [comment]
Have to look what changes are needed..

**Comment by Defragster** [comment]
Yeah - I could do that as well with a DIFF. to see what the key was ... first guess is the 'pre-load' on itcm.  But I didn't save your version off yet - and it looks like I dumped ALL my other old Arduino trees that might have that version of .LD's before Paul made other recent changes.

**Comment by FrankBoesing** [comment]
You can try this: https://github.com/FrankBoesing/snippets/blob/master/linker/experimental_imxrt1062_t41.ld
So far, it is not tested much. A  few programs I tested work... but there can steill be problems.
The size-tools reports a few bytes in ITCM. This is wrong, and a bug in the size tool.

**Comment by FrankBoesing** [comment]
Mentioned here: https://github.com/PaulStoffregen/cores/issues/589

**Comment by Defragster** [comment]
Thanks for the update Frank, I'll need to edit it for the T_4.0 as that is the board I'll be testing on

It will be a week or so before I have the hardware to test - will look at it soon.

**Comment by Defragster** [comment]
Need to try this on the Beta board. I wrote the code to write code and tested that in FLASHMEM - but will test these edits to LD

**Comment by FrankBoesing** [comment]
Ok :)
